### ISSUE TITLE
怎么设置代理

### ISSUE THREAD

**Issue by 362227** [CALTyang/115pc-docker#6]
我用的的国外的vps，我有机场代理，然后在容器运行v2ray，代理/端口是127.0.0.1:1083，代理是成功的，通过curl cip.cc查看ip也确实代理成功，但怎么让115客户端也能代理呢。或者还有什么别的方法

**Comment by CALTyang** [comment]
我自己是通过软路由，有个单独的openwrt做旁路由。所有需要走代理的机器一刀切指定了网关为软路由。提供个思路哈，如果要让115客户端走代理，我感觉配置起来会比较麻烦，我暂时没有需求，懒得折腾。祝好运 😃

**Comment by 362227** [comment]
我已经搞定了，修改了dockerfile文件
